[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/curriculum-marco-montalbano.pdf"
  status = 200
  force = true
  headers = { Content-Disposition = "attachment; filename='curriculum-marco-montalbano.pdf'" }
